apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodewebapp-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: "server-3.ozcelik.tk:5000/node-web-app"
      imagePullSecrets:
       - name: dockerreg2
---
apiVersion: v1
kind: Service
metadata:
  name: nodewebapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
